<div class="space-y-6 max-w-4xl">
    <h2 class="text-2xl font-bold text-white">Ürün Ekle</h2>
    <?php if (is_string($error) && $error !== ''): ?><div class="rounded-2xl border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-rose-200 text-sm"><?= htmlspecialchars($error, ENT_QUOTES, 'UTF-8') ?></div><?php endif; ?>
    <form method="POST" action="/admin/products/store" class="rounded-3xl border border-slate-800 bg-slate-900 p-6 space-y-5">
        <input type="hidden" name="csrf_token" value="<?= htmlspecialchars((string) $csrfToken, ENT_QUOTES, 'UTF-8') ?>">
        <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div><label class="block mb-2 text-sm text-slate-200">Grup</label><select name="group_id" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100" required><?php foreach ($groups as $group): ?><option value="<?= htmlspecialchars((string) $group['id'], ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars((string) $group['name'], ENT_QUOTES, 'UTF-8') ?></option><?php endforeach; ?></select></div>
            <div><label class="block mb-2 text-sm text-slate-200">Ad</label><input name="name" required value="<?= htmlspecialchars((string) ($old['name'] ?? ''), ENT_QUOTES, 'UTF-8') ?>" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"></div>
            <div><label class="block mb-2 text-sm text-slate-200">Slug</label><input name="slug" required value="<?= htmlspecialchars((string) ($old['slug'] ?? ''), ENT_QUOTES, 'UTF-8') ?>" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"></div>
            <div><label class="block mb-2 text-sm text-slate-200">Tip</label><select name="type" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"><option value="hosting">hosting</option><option value="server">server</option><option value="license">license</option><option value="general">general</option></select></div>
            <div><label class="block mb-2 text-sm text-slate-200">Modül</label><select name="module" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"><option value="">Seçiniz</option><option value="cpanel">cpanel</option><option value="directadmin">directadmin</option><option value="plesk">plesk</option><option value="license-api">license-api</option></select></div>
            <div><label class="block mb-2 text-sm text-slate-200">Fiyat</label><input name="price" type="number" step="0.01" min="0" value="<?= htmlspecialchars((string) ($old['price'] ?? '0.00'), ENT_QUOTES, 'UTF-8') ?>" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"></div>
            <div><label class="block mb-2 text-sm text-slate-200">Kurulum Ücreti</label><input name="setup_fee" type="number" step="0.01" min="0" value="<?= htmlspecialchars((string) ($old['setup_fee'] ?? '0.00'), ENT_QUOTES, 'UTF-8') ?>" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"></div>
            <div><label class="block mb-2 text-sm text-slate-200">Ödeme Döngüsü</label><select name="billing_cycle" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"><option value="monthly">monthly</option><option value="annually">annually</option><option value="one-time">one-time</option><option value="free">free</option></select></div>
            <div><label class="block mb-2 text-sm text-slate-200">Durum</label><select name="status" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"><option value="1">Aktif</option><option value="0">Pasif</option></select></div>
        </div>
        <div><label class="block mb-2 text-sm text-slate-200">Açıklama</label><textarea name="description" rows="4" class="w-full rounded-2xl border border-slate-700 bg-slate-950 px-4 py-3 text-slate-100"><?= htmlspecialchars((string) ($old['description'] ?? ''), ENT_QUOTES, 'UTF-8') ?></textarea></div>
        <div class="flex gap-3"><button class="px-5 py-3 rounded-2xl bg-gradient-to-r from-indigo-500 to-violet-600 text-white" type="submit">Kaydet</button><a href="/admin/products" class="px-5 py-3 rounded-2xl border border-slate-700 text-slate-300">Geri</a></div>
    </form>
</div>
